# Adaptations to make it run on GKE Cluster:
# - added 'hostname' necessary for 'postgres-backup' CronJob
# - populate Values with parameters of Google Cloud DB for Postgres instance
apiVersion: v1
kind: Secret
metadata:
  name: polls-secret
stringData:
  username: postgres
  password: 
  dbname: postgres
  hostname: 
  database_url: postgres://postgres:<password>@<hostname>/postgres
