# Adaptations to make it run on GKE Cluster:
# - added 'hostname' necessary for 'postgres-backup' CronJob
# - populate Values with parameters of Google Cloud DB for Postgres instance
apiVersion: v1
kind: Secret
metadata:
  name: polls-secret
stringData:
  username: postgres
  password: JsGmpa381jbLoI1M
  dbname: postgres
  hostname: 10.13.96.5
  database_url: postgres://postgres:JsGmpa381jbLoI1M@10.13.96.5/postgres
