# Adaptations to make it run on GKE Cluster:
# Since Postgres 11.4 Image complains about "lost+found" folder in
# "/var/lib/postgresql/data" directory,
# which is due to Linux formating of Google Kubernetes Persistent Volume
# mounted to this directory, we have to specify a subdirectory to hold
# Postgres Database file with PGDATA Environment Variable
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      containers:
      - image: postgres:11.4
        name: db
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: polls-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: polls-secret
              key: username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: polls-secret
              key: dbname
        - name: PGDATA # new Environment Variable
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
